# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/AppInsightsTestPublisher.sln
    - name: Build
      run: dotnet build --no-restore src/AppInsightsTestPublisher.csproj -c Release
    - name: Get AssemblyVersion
      id: get_version
      run: |
        $version = (Get-Item /home/runner/work/AppInsightsTestPublisher/AppInsightsTestPublisher/src/bin/Release/net8.0/AppInsightsTestPublisher.dll | Select-Object -ExpandProperty VersionInfo).ProductVersion
        $env:VERSION=$version
        echo "VERSION=$version" >> $env:GITHUB_ENV
      shell: pwsh
    - name: Pack
      run: dotnet pack -p:PackageVersion=$env:VERSION
